server:
  port: 2004

spring:
  application:
    name: challenge-01

  datasource:
    url: jdbc:postgresql://localhost:5432/tech-challenge-01
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

security:
  token:
    expire-length: 3600000